platform :ios, '15.0'

target 'StapeSampleApp' do
  use_frameworks!
  
  pod 'FirebaseAnalytics'
end

target 'TPTStapeSDK' do
  use_frameworks!

  target 'TPTStapeSDKTests' do
    pod 'InstantMock'
    pod 'Nimble'
  end
end
